### ISSUE TITLE
Kataloge lassen sich bearbeiten

### ISSUE THREAD

**Issue by Magichoco** [plab-inc/ReqPal#118]
Nutzer hätten gerne die Möglichkeit, Kataloge direkt in der App zu bearbeiten, sodass Änderungen nicht mehr durch das erneute Hochladen eines Katalogs erfolgen müssen.

- [ ] Hochgeladene Kataloge lassen sich in der App bearbeiten und ändern:
- [x] Edit Button der Zeile editierbar schaltet
- [ ] DB Services um Funktionen zum Update der DB erweitern:
- [x] Update Requirement
- [x] Update Product Details in Requirement 
- [ ] Delete Product (siehe #181)
- [x] Add Product (siehe #181)
- [x] Qualifikation lässt sich über Slider einstellen
- [x] Delete Requirement
- [x] Add Requirement
- [x] Update Product -> Name könnte problematisch werden (siehe #181)
- [x] Weiterhin könnte beim Laden der Tabelle auch einmal der ganze Katalog oder die angeforderten Einträge pro Seite (50 oder so) in den Store geladen werden
- [x] Schauen ob ein Popup besser ist als eine EditRequirement Component
- [x] Requirements CRUD Operationen richtig absichern auf Datenbank (UI/Policies)
- [ ] Products CRUD Operationen richtig absichern auf Datenbank (UI/Policies)
- [x] Katalognamen editierbar machen
- [x] Kataloge lassen sich über die App erstellen
- [x] Unique Regeln der Kataloge/RequirementProducts durch Hinweise für den Nutzer anzeigen
- [ ] Unique Regeln der Products durch Hinweise für den Nutzer anzeigen

**Comment by TheLethalGoose** [comment]
Branch enthällt noch Type errors
